name: xcode-unit-tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: |
        xcodebuild test \
          -project DegreeCalculator.xcodeproj \
          -scheme DegreeCalculator \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
          -enableCodeCoverage YES | tee xcodebuild.log
          
    - name: Install xcpretty
      run: gem install xcpretty

    - name: Format output with xcpretty
      run: |
        cat xcodebuild.log | xcpretty

    - name: Install xcbeautify
      run: brew install xcbeautify
      
    - name: Format output with xcbeautify
      run: |
        brew install xcbeautify
        cat xcodebuild.log | xcbeautify

